In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
voc_size=10000

In [6]:
one_hot_repre=[one_hot(words,voc_size)for words in sent]
one_hot_repre

[[2016, 8807, 1173, 9921],
 [2016, 8807, 1173, 8283],
 [2016, 1737, 1173, 5902],
 [515, 5860, 6332, 3473, 4844],
 [515, 5860, 6332, 3473, 7615],
 [3728, 2016, 8739, 1173, 9003],
 [2212, 2543, 5205, 3473]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=6
embedded_sent=pad_sequences(one_hot_repre,padding='post',maxlen=sent_length)
embedded_sent

array([[2016, 8807, 1173, 9921,    0,    0],
       [2016, 8807, 1173, 8283,    0,    0],
       [2016, 1737, 1173, 5902,    0,    0],
       [ 515, 5860, 6332, 3473, 4844,    0],
       [ 515, 5860, 6332, 3473, 7615,    0],
       [3728, 2016, 8739, 1173, 9003,    0],
       [2212, 2543, 5205, 3473,    0,    0]], dtype=int32)

In [10]:
dim=10

In [17]:
model=Sequential()
model.add(Embedding(voc_size,dim))
model.compile('adam','mse')

In [20]:
model.summary()

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_5 (Embedding)         │ (7, 6, 10)             │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [22]:
model.predict(embedded_sent)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step


array([[[ 0.01275856, -0.03515635, -0.01145821,  0.01491364,
         -0.03315343,  0.02447932, -0.00960728,  0.02478975,
          0.03700509, -0.02433659],
        [ 0.04401745, -0.03953325,  0.00950769,  0.01341698,
         -0.01934182,  0.03404654, -0.03419591, -0.02667589,
         -0.04711287,  0.04772014],
        [ 0.02945212, -0.02588288,  0.00395211, -0.01622573,
          0.01804593, -0.02592374, -0.02378204,  0.01338643,
         -0.0333889 , -0.04762563],
        [ 0.02775352,  0.02874097,  0.03540769,  0.03989029,
         -0.01379762, -0.03305458, -0.00916648, -0.02186054,
          0.00763767, -0.0397575 ],
        [-0.04083116,  0.01429452, -0.04928216, -0.00570133,
          0.00185785,  0.00504696,  0.01331004,  0.03090528,
          0.03919056,  0.02818617],
        [-0.04083116,  0.01429452, -0.04928216, -0.00570133,
          0.00185785,  0.00504696,  0.01331004,  0.03090528,
          0.03919056,  0.02818617]],

       [[ 0.01275856, -0.03515635, -0.01145821,  0

In [23]:
embedded_sent[0]

array([2016, 8807, 1173, 9921,    0,    0], dtype=int32)